version: '3.8'

services:
  go2_ros2_sdk_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: go2_ros2_sdk_image
    container_name: go2_ros2_sdk_container
    command: tail -f /dev/null
    environment:
      - ROBOT_IP=192.168.98.11
      - CONN_TYPE=cyclonedds  # 或/or  webrtc
